/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("table_name").del();
  await knex("table_name").insert([
    { id: 1, colName: "rowValue1" },
    { id: 2, colName: "rowValue2" },
    { id: 3, colName: "rowValue3" },
  ]);
};
/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      userId: 1,
      name: "John",
      location: "New York",
      avatar: "http://localhost:8080/user1.png",
      bio: "I love to travel",
      language1: "English",
      language2: "French",
      language3: "Spanish",
      language4: "German",
      language5: "Italian",
      language6: "Japanese",
    },
    {
      userId: 2,
      name: "Sarah",
      avatar: "http://localhost:8080/user2.png",
      location: "Paris",
      bio: "Bonjour!",
      language1: "French",
      language2: "English",
      language3: "German",
      language4: "Spanish",
      language5: "Italian",
      language6: "Japanese",
    },
    {
      userId: 3,
      name: "Alex",
      location: "Barcelona",
      avatar: "http://localhost:8080/user3.png",
      bio: "Hola!",
      language1: "Japanese",
      language2: "English",
      language3: "Spanish",
      language4: "French",
      language5: "Italian",
      language6: "German",
    },
    {
      userId: 4,
      name: "Emily",
      location: "New York",
      avatar: "http://localhost:8080/user4.png",
      bio: "I enjoy playing the piano",
      language1: "English",
      language2: "Spanish",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 5,
      name: "David",
      location: "Barcelona",
      avatar: "http://localhost:8080/user5.png",
      bio: "¡Hola!",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 6,
      name: "Alessandra",
      location: "Paris",
      avatar: "http://localhost:8080/user6.png",
      bio: "Bonjour je m'appelle Alessandra!",
      language1: "Italian",
      language2: "English",
      language3: "French",
      language4: "Spanish",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 7,
      name: "Luis",
      location: "New York",
      avatar: "http://localhost:8080/user7.png",
      bio: "hi guys",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 8,
      name: "Marta",
      location: "Barcelona",
      avatar: "http://localhost:8080/user8.png",
      bio: "Me encanta la playa",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 9,
      name: "Thomas",
      location: "New York",
      avatar: "http://localhost:8080/user9.png",
      bio: "Ich mag Fußball",
      language1: "German",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "Spanish",
    },
    {
      userId: 10,
      name: "Yuuki",
      location: "Barcelona",
      avatar: "http://localhost:8080/user10.png",
      bio: "Hola!",
      language1: "Japanese",
      language2: "English",
      language3: "Spanish",
      language4: "French",
      language5: "Italian",
      language6: "German",
    },
    {
      userId: 11,
      name: "Maria",
      location: "Paris",
      avatar: "http://localhost:8080/user11.png",
      bio: "Je suis fan de la cuisine française",
      language1: "French",
      language2: "English",
      language3: "Spanish",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 12,
      name: "Paolo",
      location: "Paris",
      avatar: "http://localhost:8080/user12.png",
      bio: "Mi piace fare sport",
      language1: "Italian",
      language2: "English",
      language3: "French",
      language4: "Spanish",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 13,
      name: "Johannes",
      location: "New York",
      avatar: "http://localhost:8080/user13.png",
      bio: "Ich reise gerne",
      language1: "German",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "Spanish",
    },
    {
      userId: 14,
      name: "Akiko",
      location: "Barcelona",
      avatar: "http://localhost:8080/user14.png",
      bio: "Hola",
      language1: "French",
      language2: "English",
      language3: "Spanish",
      language4: "French",
      language5: "Italian",
      language6: "German",
    },
    {
      userId: 15,
      name: "Olivia",
      location: "New York",
      avatar: "http://localhost:8080/user15.png",
      bio: "I enjoy hiking and camping",
      language1: "English",
      language2: "Spanish",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 16,
      name: "Lucas",
      location: "Barcelona",
      avatar: "http://localhost:8080/user16.png",
      bio: "Me gusta la música",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 17,
      name: "Elena",
      location: "Paris",
      avatar: "http://localhost:8080/user17.png",
      bio: "Mi piace viaggiare",
      language1: "Italian",
      language2: "English",
      language3: "French",
      language4: "Spanish",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 18,
      name: "Sophie",
      location: "Paris",
      avatar: "http://localhost:8080/user18.png",
      bio: "J'aime aller au cinéma",
      language1: "French",
      language2: "English",
      language3: "Spanish",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      userId: 19,
      name: "Sophie",
      location: "New York",
      avatar: "http://localhost:8080/user19.png",
      bio: "Ich mag Kunst",
      language1: "German",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "Spanish",
    },
    {
      userId: 20,
      name: "Carlos",
      location: "Barcelona",
      avatar: "http://localhost:8080/user20.png",
      bio: "Me gusta la naturaleza",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "German",
      language5: "italian",
      language6: "Japanese",
    },
  ]);
};
