/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: 1,
      name: "John",
      location: "New York",
      avatar: "http://localhost:8080/user1.png",
      bio: "I love to travel",
      language1: "English",
      language2: "French",
      language3: "Spanish",
      language4: "German",
      language5: "Italian",
      language6: "Japanese",
    },
    {
      id: 2,
      name: "Sarah Johnson",
      avatar: "http://localhost:8080/user2.png",
      location: "Paris",
      bio: "Bonjour!",
      language1: "French",
      language2: "English",
      language3: "German",
      language4: "Spanish",
      language5: "Italian",
      language6: "Japanese",
    },
    {
      id: 3,
      name: "Alex Kim",
      location: "Tokyo",
      avatar: "http://localhost:8080/user3.png",
      bio: "こんにちは！",
      language1: "Japanese",
      language2: "English",
      language3: "Spanish",
      language4: "French",
      language5: "Italian",
      language6: "German",
    },
    {
      id: 4,
      name: "Emily Lee",
      location: "New York",
      avatar: "http://localhost:8080/user4.png",
      bio: "I enjoy playing the piano",
      language1: "English",
      language2: "Spanish",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 5,
      name: "David Garcia",
      location: "Barcelona",
      avatar: "http://localhost:8080/user5.png",
      bio: "¡Hola!",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 6,
      name: "Alessandra Rossi",
      location: "Rome",
      avatar: "http://localhost:8080/user6.png",
      bio: "Ciao!",
      language1: "Italian",
      language2: "English",
      language3: "French",
      language4: "Spanish",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 7,
      name: "Luis Hernandez",
      location: "New York",
      avatar: "http://localhost:8080/user7.png",
      bio: "hi guys",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 8,
      name: "Marta Rodriguez",
      location: "Barcelona",
      avatar: "http://localhost:8080/user8.png",
      bio: "Me encanta la playa",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 9,
      name: "Thomas Müller",
      location: "Berlin",
      avatar: "http://localhost:8080/user9.png",
      bio: "Ich mag Fußball",
      language1: "German",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "Spanish",
    },
    {
      id: 10,
      name: "Yuuki Nakamura",
      location: "Tokyo",
      avatar: "http://localhost:8080/user10.png",
      bio: "私は寿司が好きです",
      language1: "Japanese",
      language2: "English",
      language3: "Spanish",
      language4: "French",
      language5: "Italian",
      language6: "German",
    },
    {
      id: 11,
      name: "Maria Sanchez",
      location: "Paris",
      avatar: "http://localhost:8080/user11.png",
      bio: "Je suis fan de la cuisine française",
      language1: "French",
      language2: "English",
      language3: "Spanish",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 12,
      name: "Paolo Bianchi",
      location: "Rome",
      avatar: "http://localhost:8080/user12.png",
      bio: "Mi piace fare sport",
      language1: "Italian",
      language2: "English",
      language3: "French",
      language4: "Spanish",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 13,
      name: "Johannes Schmidt",
      location: "Berlin",
      avatar: "http://localhost:8080/user13.png",
      bio: "Ich reise gerne",
      language1: "German",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "Spanish",
    },
    {
      id: 14,
      name: "Akiko Tanaka",
      location: "Tokyo",
      avatar: "http://localhost:8080/user14.png",
      bio: "私は映画が好きです",
      language1: "Japanese",
      language2: "English",
      language3: "Spanish",
      language4: "French",
      language5: "Italian",
      language6: "German",
    },
    {
      id: 15,
      name: "Olivia Jones",
      location: "New York",
      avatar: "http://localhost:8080/user15.png",
      bio: "I enjoy hiking and camping",
      language1: "English",
      language2: "Spanish",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 16,
      name: "Lucas Martin",
      location: "Barcelona",
      avatar: "http://localhost:8080/user16.png",
      bio: "Me gusta la música",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 17,
      name: "Elena Russo",
      location: "Rome",
      avatar: "http://localhost:8080/user17.png",
      bio: "Mi piace viaggiare",
      language1: "Italian",
      language2: "English",
      language3: "French",
      language4: "Spanish",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 18,
      name: "Sophie Laurent",
      location: "Paris",
      avatar: "http://localhost:8080/user18.png",
      bio: "J'aime aller au cinéma",
      language1: "French",
      language2: "English",
      language3: "Spanish",
      language4: "Italian",
      language5: "Japanese",
      language6: "German",
    },
    {
      id: 19,
      name: "Sophie Müller",
      location: "Berlin",
      avatar: "http://localhost:8080/user19.png",
      bio: "Ich mag Kunst",
      language1: "German",
      language2: "English",
      language3: "French",
      language4: "Italian",
      language5: "Japanese",
      language6: "Spanish",
    },
    {
      id: 20,
      name: "Carlos Hernandez",
      location: "Barcelona",
      avatar: "http://localhost:8080/user20.png",
      bio: "Me gusta la naturaleza",
      language1: "Spanish",
      language2: "English",
      language3: "French",
      language4: "German",
      language5: "italian",
      language6: "Japanese",
    },
  ]);
};
